[package]
name = "docker-proxy"
version = "0.1.0"
edition = "2018"

[dependencies]
thrussh = "0.33.5"
thrussh-keys = "0.21.0"
tokio = "1.10.0"
futures = "0.3.16"
anyhow = "1.0.43"
log = "0.4.14"
env_logger = "0.9.0"